# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 905)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rsc/test.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_tool = QtWidgets.QWidget(self.centralwidget)
        self.top_tool.setMinimumSize(QtCore.QSize(0, 60))
        self.top_tool.setMaximumSize(QtCore.QSize(16777215, 65))
        self.top_tool.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.top_tool.setObjectName("top_tool")
        self.redo_btn = QtWidgets.QToolButton(self.top_tool)
        self.redo_btn.setGeometry(QtCore.QRect(290, 0, 60, 60))
        self.redo_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.redo_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.redo_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("rsc/redo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redo_btn.setIcon(icon1)
        self.redo_btn.setIconSize(QtCore.QSize(50, 50))
        self.redo_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.redo_btn.setObjectName("redo_btn")
        self.reboot_btn = QtWidgets.QToolButton(self.top_tool)
        self.reboot_btn.setGeometry(QtCore.QRect(406, 0, 60, 60))
        self.reboot_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.reboot_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.reboot_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("rsc/reboot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reboot_btn.setIcon(icon2)
        self.reboot_btn.setIconSize(QtCore.QSize(40, 40))
        self.reboot_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.reboot_btn.setObjectName("reboot_btn")
        self.save_btn = QtWidgets.QToolButton(self.top_tool)
        self.save_btn.setGeometry(QtCore.QRect(0, 0, 60, 60))
        self.save_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.save_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.save_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("rsc/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon3)
        self.save_btn.setIconSize(QtCore.QSize(40, 40))
        self.save_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.save_btn.setObjectName("save_btn")
        self.delete_btn = QtWidgets.QToolButton(self.top_tool)
        self.delete_btn.setGeometry(QtCore.QRect(464, 0, 60, 60))
        self.delete_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.delete_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.delete_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("rsc/delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon4)
        self.delete_btn.setIconSize(QtCore.QSize(40, 40))
        self.delete_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.delete_btn.setObjectName("delete_btn")
        self.backward_btn = QtWidgets.QToolButton(self.top_tool)
        self.backward_btn.setGeometry(QtCore.QRect(116, 0, 60, 60))
        self.backward_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.backward_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.backward_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("rsc/back .ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backward_btn.setIcon(icon5)
        self.backward_btn.setIconSize(QtCore.QSize(40, 40))
        self.backward_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.backward_btn.setObjectName("backward_btn")
        self.saveas_btn = QtWidgets.QToolButton(self.top_tool)
        self.saveas_btn.setGeometry(QtCore.QRect(58, 0, 60, 60))
        self.saveas_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.saveas_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.saveas_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("rsc/saveas.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveas_btn.setIcon(icon6)
        self.saveas_btn.setIconSize(QtCore.QSize(40, 40))
        self.saveas_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.saveas_btn.setObjectName("saveas_btn")
        self.forward_btn = QtWidgets.QToolButton(self.top_tool)
        self.forward_btn.setGeometry(QtCore.QRect(174, 0, 60, 60))
        self.forward_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.forward_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.forward_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("rsc/forward.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward_btn.setIcon(icon7)
        self.forward_btn.setIconSize(QtCore.QSize(40, 40))
        self.forward_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.forward_btn.setObjectName("forward_btn")
        self.undo_btn = QtWidgets.QToolButton(self.top_tool)
        self.undo_btn.setGeometry(QtCore.QRect(232, 0, 60, 60))
        self.undo_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.undo_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.undo_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("rsc/undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_btn.setIcon(icon8)
        self.undo_btn.setIconSize(QtCore.QSize(50, 50))
        self.undo_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.undo_btn.setObjectName("undo_btn")
        self.start_btn = QtWidgets.QToolButton(self.top_tool)
        self.start_btn.setGeometry(QtCore.QRect(348, 0, 60, 60))
        self.start_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.start_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.start_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("rsc/start.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_btn.setIcon(icon9)
        self.start_btn.setIconSize(QtCore.QSize(40, 40))
        self.start_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.start_btn.setObjectName("start_btn")
        self.for_cover = QtWidgets.QLabel(self.top_tool)
        self.for_cover.setGeometry(QtCore.QRect(520, 0, 60, 60))
        self.for_cover.setMinimumSize(QtCore.QSize(0, 60))
        self.for_cover.setMaximumSize(QtCore.QSize(16777215, 60))
        self.for_cover.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.for_cover.setObjectName("for_cover")
        self.test_btn = QtWidgets.QPushButton(self.top_tool)
        self.test_btn.setGeometry(QtCore.QRect(760, 20, 75, 23))
        self.test_btn.setObjectName("test_btn")
        self.save_btn.raise_()
        self.saveas_btn.raise_()
        self.backward_btn.raise_()
        self.forward_btn.raise_()
        self.undo_btn.raise_()
        self.redo_btn.raise_()
        self.start_btn.raise_()
        self.reboot_btn.raise_()
        self.delete_btn.raise_()
        self.for_cover.raise_()
        self.test_btn.raise_()
        self.verticalLayout.addWidget(self.top_tool)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_navbar = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_navbar.sizePolicy().hasHeightForWidth())
        self.left_navbar.setSizePolicy(sizePolicy)
        self.left_navbar.setMinimumSize(QtCore.QSize(50, 0))
        self.left_navbar.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_navbar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(55, 57, 68);")
        self.left_navbar.setObjectName("left_navbar")
        self.toolButton = QtWidgets.QToolButton(self.left_navbar)
        self.toolButton.setGeometry(QtCore.QRect(0, 0, 50, 51))
        self.toolButton.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.toolButton.setStyleSheet("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("rsc/item.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon10)
        self.toolButton.setIconSize(QtCore.QSize(60, 60))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.left_navbar)
        self.show_info = QtWidgets.QWidget(self.widget)
        self.show_info.setMinimumSize(QtCore.QSize(190, 800))
        self.show_info.setMaximumSize(QtCore.QSize(190, 1400))
        self.show_info.setStyleSheet("background-color: rgb(230, 237, 255);")
        self.show_info.setObjectName("show_info")
        self.terminal_info = QtWidgets.QTextBrowser(self.show_info)
        self.terminal_info.setGeometry(QtCore.QRect(0, 290, 191, 461))
        self.terminal_info.setStyleSheet("background-color: rgb(192, 192, 255);")
        self.terminal_info.setObjectName("terminal_info")
        self.horizontalLayout.addWidget(self.show_info)
        self.middle_change = QtWidgets.QWidget(self.widget)
        self.middle_change.setMinimumSize(QtCore.QSize(500, 800))
        self.middle_change.setMaximumSize(QtCore.QSize(1000, 1400))
        self.middle_change.setStyleSheet("background-color: rgb(249, 249, 249);")
        self.middle_change.setObjectName("middle_change")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.middle_change)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.jump_layout = QtWidgets.QGridLayout()
        self.jump_layout.setObjectName("jump_layout")
        self.gridLayout_2.addLayout(self.jump_layout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.middle_change)
        self.blank = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blank.sizePolicy().hasHeightForWidth())
        self.blank.setSizePolicy(sizePolicy)
        self.blank.setMaximumSize(QtCore.QSize(200000, 16777215))
        self.blank.setObjectName("blank")
        self.horizontalLayout.addWidget(self.blank)
        self.right_navbar_2 = QtWidgets.QWidget(self.widget)
        self.right_navbar_2.setMinimumSize(QtCore.QSize(150, 0))
        self.right_navbar_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.right_navbar_2.setStyleSheet("background-color: rgb(217, 218, 227);")
        self.right_navbar_2.setObjectName("right_navbar_2")
        self.right_unfold_2 = QtWidgets.QToolButton(self.right_navbar_2)
        self.right_unfold_2.setGeometry(QtCore.QRect(0, 0, 150, 31))
        self.right_unfold_2.setMinimumSize(QtCore.QSize(150, 0))
        self.right_unfold_2.setMaximumSize(QtCore.QSize(150, 16777215))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("rsc/r_fold.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_unfold_2.setIcon(icon11)
        self.right_unfold_2.setIconSize(QtCore.QSize(20, 20))
        self.right_unfold_2.setObjectName("right_unfold_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.right_navbar_2)
        self.toolButton_3.setGeometry(QtCore.QRect(0, 30, 150, 41))
        self.toolButton_3.setMinimumSize(QtCore.QSize(150, 0))
        self.toolButton_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.right_navbar_2)
        self.right_navbar = QtWidgets.QWidget(self.widget)
        self.right_navbar.setMinimumSize(QtCore.QSize(50, 0))
        self.right_navbar.setMaximumSize(QtCore.QSize(50, 16777215))
        self.right_navbar.setStyleSheet("background-color: rgb(217, 218, 227);")
        self.right_navbar.setObjectName("right_navbar")
        self.right_unfold = QtWidgets.QToolButton(self.right_navbar)
        self.right_unfold.setGeometry(QtCore.QRect(0, 0, 50, 31))
        self.right_unfold.setMinimumSize(QtCore.QSize(50, 0))
        self.right_unfold.setMaximumSize(QtCore.QSize(50, 16777215))
        self.right_unfold.setIcon(icon5)
        self.right_unfold.setIconSize(QtCore.QSize(20, 20))
        self.right_unfold.setObjectName("right_unfold")
        self.toolButton_2 = QtWidgets.QToolButton(self.right_navbar)
        self.toolButton_2.setGeometry(QtCore.QRect(0, 30, 50, 41))
        self.toolButton_2.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.right_navbar)
        self.right_navbar.raise_()
        self.right_navbar_2.raise_()
        self.middle_change.raise_()
        self.left_navbar.raise_()
        self.show_info.raise_()
        self.blank.raise_()
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setMinimumSize(QtCore.QSize(0, 0))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())

        self.retranslateUi(MainWindow)
        self.right_unfold_2.clicked.connect(MainWindow.showMaximized)
        self.right_unfold.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MSE材料科学继承计算系统"))
        self.redo_btn.setText(_translate("MainWindow", "重做"))
        self.reboot_btn.setText(_translate("MainWindow", "重启"))
        self.save_btn.setText(_translate("MainWindow", "保存"))
        self.delete_btn.setText(_translate("MainWindow", "删除"))
        self.backward_btn.setText(_translate("MainWindow", "后退"))
        self.saveas_btn.setText(_translate("MainWindow", "另存为"))
        self.forward_btn.setText(_translate("MainWindow", "前进"))
        self.undo_btn.setText(_translate("MainWindow", "撤销"))
        self.start_btn.setText(_translate("MainWindow", "开始"))
        self.for_cover.setText(_translate("MainWindow", "覆盖用"))
        self.test_btn.setText(_translate("MainWindow", "test"))
        self.toolButton.setText(_translate("MainWindow", "000"))
        self.terminal_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">aowrgnoigawn</p></body></html>"))
        self.right_unfold_2.setText(_translate("MainWindow", "right_unfold"))
        self.toolButton_3.setText(_translate("MainWindow", "当前"))
        self.right_unfold.setText(_translate("MainWindow", "right_unfold"))
        self.toolButton_2.setText(_translate("MainWindow", "当前"))
        self.menu_2.setTitle(_translate("MainWindow", "显示"))
        self.menu_3.setTitle(_translate("MainWindow", "窗口"))
        self.menu_5.setTitle(_translate("MainWindow", "账户"))
        self.menu_6.setTitle(_translate("MainWindow", "帮助"))
        self.file.setTitle(_translate("MainWindow", "文件"))
        self.menu_4.setTitle(_translate("MainWindow", "设置"))

